apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins
spec:
  containers:
    - name: maven
      image: maven:3.8.1-jdk-8
      command:
        - sleep
      args:
        - "99d"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - "9999999"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-registry
        items:
          - key: .dockerconfigjson
            path: config.json