apiVersion: v1
kind: Pod
metadata:
  name: sdkman
  namespace: jenkins
  labels:
    some-label: some-label-value
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: sdkman
      image: 74734589924/sdkman:1.0
#      ttyEnabled: true
      command:
        - sleep
      args:
        - "99d"